# This file was generated by the docusign_rest:generate_config rake task.
# You can run 'rake docusign_rest:generate_config' as many times as you need
# to replace the content of this file with a new config.

require 'docusign_rest'

DocusignRest.configure do |config|
  config.username       = ENV["DOCUSIGN_USERNAME"]
  config.password       = ENV["DOCUSIGN_PASSWORD"]
  config.integrator_key = ENV["DOCUSIGN_INTEGRATOR_KEY"]
  config.account_id     = ENV["DOCUSIGN_ACCOUNT_ID"]
  if Rails.env.production?
    config.endpoint       = "https://na2.docusign.net/restapi"
    config.api_version    = "v2"
  end
end

